print("|-----------------------------|")
print("|Remetente: Celio Ludwig Slomp|")
print("|Rua Maracajá, n. 116         |")
print("|Bairro Quintino              |")
print("|CEP 89120-000                |")
print("|-----------------------------|")