print("|-----------------------------|")
print("|Remetente: Celio Ludwig Slomp|")
print("|Endereço        |")
print("|Bairro              |")
print("|CEP XXX                |")
print("|-----------------------------|")
